import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../public/globals.css";
import "../public/custom.css";
import { Suspense } from "react";
import Loading from "@/app/loading";
import { classNames } from "@/utils/functions";

import "@fontsource/inter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body
        className={classNames(inter.className, "h-full")}
        cz-shortcut-listen="true"
      >
        <main>
          <Suspense fallback={<Loading />}>
            <div className="mx-auto flex flex-col sm:px-6 lg:px-8 h-screen">
              {children}
            </div>
          </Suspense>
        </main>
      </body>
    </html>
  );
}
