import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "@/app/loading";
import { ApolloWrapper } from "@/app/ApolloWrapper";
import AuthContextProvider from "@/app/contexts/authContext";
import {classNames} from "@/app/utils/functions";

import '@fontsource/inter';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full bg-gray-50">
        <body className={classNames(inter.className, 'h-full')} cz-shortcut-listen="true">
        <AuthContextProvider>
            <main>
                <Suspense fallback={<Loading />}>
                    <ApolloWrapper>
                        <div className="mx-auto flex flex-col sm:px-6 lg:px-8 h-screen">
                            {children}
                        </div>
                    </ApolloWrapper>
                </Suspense>
            </main>
        </AuthContextProvider>
        </body>
        </html>
    );
}
